package com.bor.eboard.reports.export;

import com.bor.eboard.reports.dto.ReportColumn;
import com.bor.eboard.reports.dto.ReportData;
import org.apache.poi.ss.usermodel.BorderStyle;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.FillPatternType;
import org.apache.poi.ss.usermodel.Font;
import org.apache.poi.ss.usermodel.HorizontalAlignment;
import org.apache.poi.ss.usermodel.IndexedColors;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.springframework.stereotype.Component;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.UncheckedIOException;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Map;

/**
 * Renders any {@link ReportData} to an .xlsx workbook: a filter-summary
 * block, a styled header row, data rows, and an optional totals row
 * (11_REPORTS.md section 12).
 */
@Component
public class ExcelReportExporter {

    private static final DateTimeFormatter STAMP =
            DateTimeFormatter.ofPattern("dd MMM yyyy HH:mm");

    public byte[] export(ReportData report) {
        try (Workbook workbook = new XSSFWorkbook();
             ByteArrayOutputStream out = new ByteArrayOutputStream()) {

            Sheet sheet = workbook.createSheet(safeSheetName(report.getReportCode()));
            int rowIdx = 0;

            CellStyle titleStyle = boldStyle(workbook, 14);
            CellStyle metaStyle = plainStyle(workbook);
            CellStyle headerStyle = headerStyle(workbook);
            CellStyle cellStyle = borderedStyle(workbook);
            CellStyle totalStyle = boldBorderedStyle(workbook);

            // Title
            Row titleRow = sheet.createRow(rowIdx++);
            writeCell(titleRow, 0, report.getTitle(), titleStyle);

            // Generated meta
            Row genRow = sheet.createRow(rowIdx++);
            writeCell(genRow, 0,
                    "Generated by " + nullToDash(report.getGeneratedByName())
                            + " on " + (report.getGeneratedAt() != null
                            ? report.getGeneratedAt().format(STAMP) : ""),
                    metaStyle);

            // Filters
            if (report.getFilterSummary() != null) {
                for (String filter : report.getFilterSummary()) {
                    Row fr = sheet.createRow(rowIdx++);
                    writeCell(fr, 0, filter, metaStyle);
                }
            }
            rowIdx++; // spacer

            // Header
            List<ReportColumn> columns = report.getColumns();
            Row headerRow = sheet.createRow(rowIdx++);
            for (int c = 0; c < columns.size(); c++) {
                writeCell(headerRow, c, columns.get(c).getHeader(), headerStyle);
            }

            // Data
            for (Map<String, Object> row : report.getRows()) {
                Row dataRow = sheet.createRow(rowIdx++);
                for (int c = 0; c < columns.size(); c++) {
                    Object value = row.get(columns.get(c).getKey());
                    writeCell(dataRow, c, value != null ? value.toString() : "", cellStyle);
                }
            }

            // Totals
            if (report.getTotals() != null && !report.getTotals().isEmpty()) {
                Row totalRow = sheet.createRow(rowIdx++);
                for (int c = 0; c < columns.size(); c++) {
                    Object total = report.getTotals().get(columns.get(c).getKey());
                    String text = c == 0 && total == null ? "Total" : (total != null ? total.toString() : "");
                    writeCell(totalRow, c, text, totalStyle);
                }
            }

            for (int c = 0; c < columns.size(); c++) {
                sheet.autoSizeColumn(c);
            }

            workbook.write(out);
            return out.toByteArray();
        } catch (IOException e) {
            throw new UncheckedIOException("Failed to export Excel report", e);
        }
    }

    private void writeCell(Row row, int col, String value, CellStyle style) {
        Cell cell = row.createCell(col);
        cell.setCellValue(value);
        cell.setCellStyle(style);
    }

    private CellStyle plainStyle(Workbook wb) {
        return wb.createCellStyle();
    }

    private CellStyle boldStyle(Workbook wb, int points) {
        CellStyle style = wb.createCellStyle();
        Font font = wb.createFont();
        font.setBold(true);
        font.setFontHeightInPoints((short) points);
        style.setFont(font);
        return style;
    }

    private CellStyle headerStyle(Workbook wb) {
        CellStyle style = borderedStyle(wb);
        Font font = wb.createFont();
        font.setBold(true);
        font.setColor(IndexedColors.WHITE.getIndex());
        style.setFont(font);
        style.setFillForegroundColor(IndexedColors.DARK_BLUE.getIndex());
        style.setFillPattern(FillPatternType.SOLID_FOREGROUND);
        style.setAlignment(HorizontalAlignment.CENTER);
        return style;
    }

    private CellStyle borderedStyle(Workbook wb) {
        CellStyle style = wb.createCellStyle();
        style.setBorderTop(BorderStyle.THIN);
        style.setBorderBottom(BorderStyle.THIN);
        style.setBorderLeft(BorderStyle.THIN);
        style.setBorderRight(BorderStyle.THIN);
        return style;
    }

    private CellStyle boldBorderedStyle(Workbook wb) {
        CellStyle style = borderedStyle(wb);
        Font font = wb.createFont();
        font.setBold(true);
        style.setFont(font);
        return style;
    }

    private String nullToDash(String value) {
        return value != null ? value : "-";
    }

    private String safeSheetName(String code) {
        if (code == null || code.isBlank()) {
            return "Report";
        }
        return code.length() > 31 ? code.substring(0, 31) : code;
    }
}
