package com.bor.eboard.reports.export;

import com.bor.eboard.reports.dto.ReportColumn;
import com.bor.eboard.reports.dto.ReportData;
import com.lowagie.text.Document;
import com.lowagie.text.Element;
import com.lowagie.text.Font;
import com.lowagie.text.FontFactory;
import com.lowagie.text.PageSize;
import com.lowagie.text.Paragraph;
import com.lowagie.text.Phrase;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import org.springframework.stereotype.Component;

import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Map;

/**
 * Renders any {@link ReportData} to a landscape A4 PDF with an official
 * header block, filter summary, a bordered data table, an optional totals
 * row, and page numbers (11_REPORTS.md section 12).
 */
@Component
public class PdfReportExporter {

    private static final DateTimeFormatter STAMP =
            DateTimeFormatter.ofPattern("dd MMM yyyy HH:mm");
    private static final Color HEADER_BG = new Color(26, 60, 110); // gov navy

    public byte[] export(ReportData report) {
        Document document = new Document(PageSize.A4.rotate(), 28, 28, 28, 36);
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        PdfWriter writer = PdfWriter.getInstance(document, out);
        writer.setPageEvent(new PageNumberFooter());
        document.open();

        // Official header
        Font orgFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 13, new Color(60, 20, 20));
        Paragraph org = new Paragraph("Board of Revenue, Government of Uttar Pradesh", orgFont);
        org.setAlignment(Element.ALIGN_CENTER);
        document.add(org);

        Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 12, HEADER_BG);
        Paragraph title = new Paragraph(report.getTitle(), titleFont);
        title.setAlignment(Element.ALIGN_CENTER);
        title.setSpacingAfter(8f);
        document.add(title);

        // Meta + filters
        Font metaFont = FontFactory.getFont(FontFactory.HELVETICA, 8, Color.DARK_GRAY);
        String meta = "Generated by " + nvl(report.getGeneratedByName())
                + " on " + (report.getGeneratedAt() != null
                ? report.getGeneratedAt().format(STAMP) : "");
        document.add(new Paragraph(meta, metaFont));
        if (report.getFilterSummary() != null && !report.getFilterSummary().isEmpty()) {
            document.add(new Paragraph(String.join("   |   ", report.getFilterSummary()), metaFont));
        }

        // Table
        List<ReportColumn> columns = report.getColumns();
        PdfPTable table = new PdfPTable(columns.size());
        table.setWidthPercentage(100);
        table.setSpacingBefore(10f);
        applyColumnWidths(table, columns);

        Font headFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 8, Color.WHITE);
        for (ReportColumn column : columns) {
            PdfPCell cell = new PdfPCell(new Phrase(column.getHeader(), headFont));
            cell.setBackgroundColor(HEADER_BG);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell.setPadding(4f);
            table.addCell(cell);
        }

        Font bodyFont = FontFactory.getFont(FontFactory.HELVETICA, 8, Color.BLACK);
        for (Map<String, Object> row : report.getRows()) {
            for (ReportColumn column : columns) {
                Object value = row.get(column.getKey());
                PdfPCell cell = new PdfPCell(
                        new Phrase(value != null ? value.toString() : "", bodyFont));
                cell.setPadding(3f);
                table.addCell(cell);
            }
        }

        if (report.getTotals() != null && !report.getTotals().isEmpty()) {
            Font totalFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 8, Color.BLACK);
            for (int c = 0; c < columns.size(); c++) {
                Object total = report.getTotals().get(columns.get(c).getKey());
                String text = c == 0 && total == null ? "Total" : (total != null ? total.toString() : "");
                PdfPCell cell = new PdfPCell(new Phrase(text, totalFont));
                cell.setBackgroundColor(new Color(235, 235, 235));
                cell.setPadding(3f);
                table.addCell(cell);
            }
        }

        if (report.getRows().isEmpty()) {
            document.add(new Paragraph(" "));
            Paragraph empty = new Paragraph("No records found for the selected filters.", metaFont);
            empty.setAlignment(Element.ALIGN_CENTER);
            document.add(empty);
        } else {
            document.add(table);
        }

        document.close();
        return out.toByteArray();
    }

    private void applyColumnWidths(PdfPTable table, List<ReportColumn> columns) {
        boolean anyHint = columns.stream().anyMatch(c -> c.getWidthHint() > 0);
        if (!anyHint) {
            return;
        }
        float[] widths = new float[columns.size()];
        for (int i = 0; i < columns.size(); i++) {
            int hint = columns.get(i).getWidthHint();
            widths[i] = hint > 0 ? hint : 1f;
        }
        try {
            table.setWidths(widths);
        } catch (Exception ignored) {
            // fall back to equal widths
        }
    }

    private String nvl(String value) {
        return value != null ? value : "-";
    }

    /** Draws "Page X" centered at the bottom of every page. */
    private static class PageNumberFooter extends com.lowagie.text.pdf.PdfPageEventHelper {
        private final Font footerFont =
                FontFactory.getFont(FontFactory.HELVETICA, 7, Color.GRAY);

        @Override
        public void onEndPage(PdfWriter writer, Document document) {
            com.lowagie.text.pdf.ColumnText.showTextAligned(
                    writer.getDirectContent(),
                    Element.ALIGN_CENTER,
                    new Phrase("Page " + writer.getPageNumber(), footerFont),
                    (document.left() + document.right()) / 2,
                    document.bottom() - 12, 0);
        }
    }
}
